//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for RequirementGrade.
const (
	E1 RequirementGrade = "E1"
	E2 RequirementGrade = "E2"
	E3 RequirementGrade = "E3"
	E4 RequirementGrade = "E4"
	E5 RequirementGrade = "E5"
	E6 RequirementGrade = "E6"
	E7 RequirementGrade = "E7"
	E8 RequirementGrade = "E8"
	E9 RequirementGrade = "E9"
)

// Defines values for GetApiMembersParamsFilter.
const (
	Disabled GetApiMembersParamsFilter = "disabled"
	Enabled  GetApiMembersParamsFilter = "enabled"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// InitialMemberRequirement Initial requirement assigned to a member
type InitialMemberRequirement struct {
	AssignedBy    string     `json:"assigned_by"`
	CompletedBy   *string    `json:"completed_by,omitempty"`
	CompletedDate *time.Time `json:"completed_date,omitempty"`
	MemberId      string     `json:"member_id"`
	RequirementId string     `json:"requirement_id"`
}

// Member defines model for Member.
type Member struct {
	Admin        bool    `json:"admin"`
	Disabled     bool    `json:"disabled"`
	FirstName    string  `json:"first_name"`
	Grade        string  `json:"grade"`
	Id           string  `json:"id"`
	LastName     string  `json:"last_name"`
	SupervisorId *string `json:"supervisor_id,omitempty"`
	Username     string  `json:"username"`
}

// MemberQualification Qualification Assigned to a member
type MemberQualification struct {
	AssignedBy      string    `json:"assigned_by"`
	DateAssigned    time.Time `json:"date_assigned"`
	MemberId        string    `json:"member_id"`
	QualificationId string    `json:"qualification_id"`
}

// Qualification defines model for Qualification.
type Qualification struct {
	Id                    string         `json:"id"`
	InitialRequirements   *[]Requirement `json:"initial_requirements,omitempty"`
	Name                  string         `json:"name"`
	Notes                 *string        `json:"notes,omitempty"`
	RecurringRequirements *[]Requirement `json:"recurring_requirements,omitempty"`
}

// Ranks defines model for Ranks.
type Ranks struct {
	E1 string `json:"E1"`
	E2 string `json:"E2"`
	E3 string `json:"E3"`
	E4 string `json:"E4"`
	E5 string `json:"E5"`
	E6 string `json:"E6"`
	E7 string `json:"E7"`
	E8 string `json:"E8"`
	E9 string `json:"E9"`
}

// RecurringMemberRequirement Recurring requirement assigned to a member
type RecurringMemberRequirement struct {
	AssignedBy        string                                 `json:"assigned_by"`
	CompletedBy       *string                                `json:"completed_by,omitempty"`
	CompletedDate     *time.Time                             `json:"completed_date,omitempty"`
	CompletionHistory []RecurringMemberRequirementCompletion `json:"completion_history"`
	Id                string                                 `json:"id"`
	MemberId          string                                 `json:"member_id"`
	RequirementId     string                                 `json:"requirement_id"`
}

// RecurringMemberRequirementCompletion Recurring requirement completion for a member
type RecurringMemberRequirementCompletion struct {
	CompletedBy    string    `json:"completed_by"`
	CompletionDate time.Time `json:"completion_date"`
	Id             string    `json:"id"`
}

// Requirement defines model for Requirement.
type Requirement struct {
	DaysValidFor    *int              `json:"days_valid_for,omitempty"`
	Grade           *RequirementGrade `json:"grade,omitempty"`
	Id              string            `json:"id"`
	Initial         bool              `json:"initial"`
	Name            string            `json:"name"`
	Notes           *string           `json:"notes,omitempty"`
	QualificationId *string           `json:"qualification_id,omitempty"`
	Reference       string            `json:"reference"`
	Type            string            `json:"type"`
}

// RequirementGrade defines model for Requirement.Grade.
type RequirementGrade string

// PostApiDisableMemberParams defines parameters for PostApiDisableMember.
type PostApiDisableMemberParams struct {
	Id string `form:"id" json:"id"`
}

// PostApiEnableMemberParams defines parameters for PostApiEnableMember.
type PostApiEnableMemberParams struct {
	Id string `form:"id" json:"id"`
}

// PostApiLoginJSONBody defines parameters for PostApiLogin.
type PostApiLoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// GetApiMemberParams defines parameters for GetApiMember.
type GetApiMemberParams struct {
	Id string `form:"id" json:"id"`
}

// PostApiMemberJSONBody defines parameters for PostApiMember.
type PostApiMemberJSONBody struct {
	Admin        bool    `json:"admin"`
	Disabled     bool    `json:"disabled"`
	FirstName    string  `json:"first_name"`
	Grade        string  `json:"grade"`
	Id           string  `json:"id"`
	LastName     string  `json:"last_name"`
	Password     *string `json:"password,omitempty"`
	SupervisorId *string `json:"supervisor_id,omitempty"`
	Username     string  `json:"username"`
}

// PutApiMemberJSONBody defines parameters for PutApiMember.
type PutApiMemberJSONBody struct {
	Admin        bool    `json:"admin"`
	Disabled     bool    `json:"disabled"`
	FirstName    string  `json:"first_name"`
	Grade        string  `json:"grade"`
	Id           string  `json:"id"`
	LastName     string  `json:"last_name"`
	Password     *string `json:"password,omitempty"`
	SupervisorId *string `json:"supervisor_id,omitempty"`
	Username     string  `json:"username"`
}

// PostApiMemberQualificationParams defines parameters for PostApiMemberQualification.
type PostApiMemberQualificationParams struct {
	MemberId        string `form:"member_id" json:"member_id"`
	QualificationId string `form:"qualification_id" json:"qualification_id"`
	AssignedBy      string `form:"assigned_by" json:"assigned_by"`
}

// GetApiMemberQualificationsParams defines parameters for GetApiMemberQualifications.
type GetApiMemberQualificationsParams struct {
	// MemberId ID of member to get qualifications for
	MemberId string `form:"member_id" json:"member_id"`
}

// GetApiMemberRequirementInitialParams defines parameters for GetApiMemberRequirementInitial.
type GetApiMemberRequirementInitialParams struct {
	MemberId      string `form:"member_id" json:"member_id"`
	RequirementId string `form:"requirement_id" json:"requirement_id"`
}

// GetApiMemberRequirementsInitialParams defines parameters for GetApiMemberRequirementsInitial.
type GetApiMemberRequirementsInitialParams struct {
	MemberId        string  `form:"member_id" json:"member_id"`
	QualificationId *string `form:"qualification_id,omitempty" json:"qualification_id,omitempty"`
}

// GetApiMemberRequirementsRecurringParams defines parameters for GetApiMemberRequirementsRecurring.
type GetApiMemberRequirementsRecurringParams struct {
	MemberId        string  `form:"member_id" json:"member_id"`
	QualificationId *string `form:"qualification_id,omitempty" json:"qualification_id,omitempty"`
}

// GetApiMemberSubordinatesParams defines parameters for GetApiMemberSubordinates.
type GetApiMemberSubordinatesParams struct {
	// MemberId ID of member to get subordinates for
	MemberId string `form:"member_id" json:"member_id"`
}

// GetApiMembersParams defines parameters for GetApiMembers.
type GetApiMembersParams struct {
	// Filter Options for filtering retrieved members. No filter returns all members
	Filter *GetApiMembersParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetApiMembersParamsFilter defines parameters for GetApiMembers.
type GetApiMembersParamsFilter string

// GetApiPotentialSupervisorsParams defines parameters for GetApiPotentialSupervisors.
type GetApiPotentialSupervisorsParams struct {
	// Grade Grade to find potential supervisors for E1-E9(case sensitive)
	Grade string `form:"grade" json:"grade"`

	// Id Member to get potential supervisors for, not required for new members
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostApiLoginJSONRequestBody defines body for PostApiLogin for application/json ContentType.
type PostApiLoginJSONRequestBody PostApiLoginJSONBody

// PostApiMemberJSONRequestBody defines body for PostApiMember for application/json ContentType.
type PostApiMemberJSONRequestBody PostApiMemberJSONBody

// PutApiMemberJSONRequestBody defines body for PutApiMember for application/json ContentType.
type PutApiMemberJSONRequestBody PutApiMemberJSONBody

// PostApiQualificationJSONRequestBody defines body for PostApiQualification for application/json ContentType.
type PostApiQualificationJSONRequestBody = Qualification

// PutApiQualificationJSONRequestBody defines body for PutApiQualification for application/json ContentType.
type PutApiQualificationJSONRequestBody = Qualification

// PostApiRequirementJSONRequestBody defines body for PostApiRequirement for application/json ContentType.
type PostApiRequirementJSONRequestBody = Requirement

// PutApiRequirementJSONRequestBody defines body for PutApiRequirement for application/json ContentType.
type PutApiRequirementJSONRequestBody = Requirement

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/disableMember)
	PostApiDisableMember(w http.ResponseWriter, r *http.Request, params PostApiDisableMemberParams)

	// (POST /api/enableMember)
	PostApiEnableMember(w http.ResponseWriter, r *http.Request, params PostApiEnableMemberParams)

	// (POST /api/login)
	PostApiLogin(w http.ResponseWriter, r *http.Request)

	// (POST /api/logout)
	PostApiLogout(w http.ResponseWriter, r *http.Request)
	// Get a member
	// (GET /api/member)
	GetApiMember(w http.ResponseWriter, r *http.Request, params GetApiMemberParams)
	// Create a member
	// (POST /api/member)
	PostApiMember(w http.ResponseWriter, r *http.Request)
	// Update an individual member
	// (PUT /api/member)
	PutApiMember(w http.ResponseWriter, r *http.Request)

	// (POST /api/member/qualification)
	PostApiMemberQualification(w http.ResponseWriter, r *http.Request, params PostApiMemberQualificationParams)

	// (GET /api/member/qualifications)
	GetApiMemberQualifications(w http.ResponseWriter, r *http.Request, params GetApiMemberQualificationsParams)

	// (GET /api/member/requirement/initial)
	GetApiMemberRequirementInitial(w http.ResponseWriter, r *http.Request, params GetApiMemberRequirementInitialParams)

	// (GET /api/member/requirements/initial)
	GetApiMemberRequirementsInitial(w http.ResponseWriter, r *http.Request, params GetApiMemberRequirementsInitialParams)

	// (GET /api/member/requirements/recurring)
	GetApiMemberRequirementsRecurring(w http.ResponseWriter, r *http.Request, params GetApiMemberRequirementsRecurringParams)

	// (GET /api/member/subordinates)
	GetApiMemberSubordinates(w http.ResponseWriter, r *http.Request, params GetApiMemberSubordinatesParams)

	// (GET /api/members)
	GetApiMembers(w http.ResponseWriter, r *http.Request, params GetApiMembersParams)

	// (GET /api/organization)
	GetApiOrganization(w http.ResponseWriter, r *http.Request)
	// Get a list of the potential supervisors for a given grade
	// (GET /api/potentialSupervisors)
	GetApiPotentialSupervisors(w http.ResponseWriter, r *http.Request, params GetApiPotentialSupervisorsParams)

	// (POST /api/qualification)
	PostApiQualification(w http.ResponseWriter, r *http.Request)

	// (PUT /api/qualification)
	PutApiQualification(w http.ResponseWriter, r *http.Request)

	// (GET /api/qualifications)
	GetApiQualifications(w http.ResponseWriter, r *http.Request)

	// (GET /api/ranks)
	GetApiRanks(w http.ResponseWriter, r *http.Request)

	// (POST /api/requirement)
	PostApiRequirement(w http.ResponseWriter, r *http.Request)

	// (PUT /api/requirement)
	PutApiRequirement(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiDisableMember operation middleware
func (siw *ServerInterfaceWrapper) PostApiDisableMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiDisableMemberParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDisableMember(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiEnableMember operation middleware
func (siw *ServerInterfaceWrapper) PostApiEnableMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiEnableMemberParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiEnableMember(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLogin operation middleware
func (siw *ServerInterfaceWrapper) PostApiLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLogout operation middleware
func (siw *ServerInterfaceWrapper) PostApiLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMember operation middleware
func (siw *ServerInterfaceWrapper) GetApiMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMember(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiMember operation middleware
func (siw *ServerInterfaceWrapper) PostApiMember(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiMember operation middleware
func (siw *ServerInterfaceWrapper) PutApiMember(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiMemberQualification operation middleware
func (siw *ServerInterfaceWrapper) PostApiMemberQualification(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiMemberQualificationParams

	// ------------- Required query parameter "member_id" -------------

	if paramValue := r.URL.Query().Get("member_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "member_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "member_id", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	// ------------- Required query parameter "qualification_id" -------------

	if paramValue := r.URL.Query().Get("qualification_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "qualification_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "qualification_id", r.URL.Query(), &params.QualificationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "qualification_id", Err: err})
		return
	}

	// ------------- Required query parameter "assigned_by" -------------

	if paramValue := r.URL.Query().Get("assigned_by"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "assigned_by"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "assigned_by", r.URL.Query(), &params.AssignedBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assigned_by", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiMemberQualification(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMemberQualifications operation middleware
func (siw *ServerInterfaceWrapper) GetApiMemberQualifications(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberQualificationsParams

	// ------------- Required query parameter "member_id" -------------

	if paramValue := r.URL.Query().Get("member_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "member_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "member_id", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMemberQualifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMemberRequirementInitial operation middleware
func (siw *ServerInterfaceWrapper) GetApiMemberRequirementInitial(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberRequirementInitialParams

	// ------------- Required query parameter "member_id" -------------

	if paramValue := r.URL.Query().Get("member_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "member_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "member_id", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	// ------------- Required query parameter "requirement_id" -------------

	if paramValue := r.URL.Query().Get("requirement_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "requirement_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "requirement_id", r.URL.Query(), &params.RequirementId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requirement_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMemberRequirementInitial(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMemberRequirementsInitial operation middleware
func (siw *ServerInterfaceWrapper) GetApiMemberRequirementsInitial(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberRequirementsInitialParams

	// ------------- Required query parameter "member_id" -------------

	if paramValue := r.URL.Query().Get("member_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "member_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "member_id", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	// ------------- Optional query parameter "qualification_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "qualification_id", r.URL.Query(), &params.QualificationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "qualification_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMemberRequirementsInitial(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMemberRequirementsRecurring operation middleware
func (siw *ServerInterfaceWrapper) GetApiMemberRequirementsRecurring(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberRequirementsRecurringParams

	// ------------- Required query parameter "member_id" -------------

	if paramValue := r.URL.Query().Get("member_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "member_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "member_id", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	// ------------- Optional query parameter "qualification_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "qualification_id", r.URL.Query(), &params.QualificationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "qualification_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMemberRequirementsRecurring(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMemberSubordinates operation middleware
func (siw *ServerInterfaceWrapper) GetApiMemberSubordinates(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberSubordinatesParams

	// ------------- Required query parameter "member_id" -------------

	if paramValue := r.URL.Query().Get("member_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "member_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "member_id", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMemberSubordinates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMembers operation middleware
func (siw *ServerInterfaceWrapper) GetApiMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMembersParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMembers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetApiOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPotentialSupervisors operation middleware
func (siw *ServerInterfaceWrapper) GetApiPotentialSupervisors(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiPotentialSupervisorsParams

	// ------------- Required query parameter "grade" -------------

	if paramValue := r.URL.Query().Get("grade"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "grade"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "grade", r.URL.Query(), &params.Grade)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "grade", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPotentialSupervisors(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiQualification operation middleware
func (siw *ServerInterfaceWrapper) PostApiQualification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiQualification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiQualification operation middleware
func (siw *ServerInterfaceWrapper) PutApiQualification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiQualification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiQualifications operation middleware
func (siw *ServerInterfaceWrapper) GetApiQualifications(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiQualifications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiRanks operation middleware
func (siw *ServerInterfaceWrapper) GetApiRanks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiRanks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRequirement operation middleware
func (siw *ServerInterfaceWrapper) PostApiRequirement(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRequirement(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiRequirement operation middleware
func (siw *ServerInterfaceWrapper) PutApiRequirement(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiRequirement(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/disableMember", wrapper.PostApiDisableMember)
	m.HandleFunc("POST "+options.BaseURL+"/api/enableMember", wrapper.PostApiEnableMember)
	m.HandleFunc("POST "+options.BaseURL+"/api/login", wrapper.PostApiLogin)
	m.HandleFunc("POST "+options.BaseURL+"/api/logout", wrapper.PostApiLogout)
	m.HandleFunc("GET "+options.BaseURL+"/api/member", wrapper.GetApiMember)
	m.HandleFunc("POST "+options.BaseURL+"/api/member", wrapper.PostApiMember)
	m.HandleFunc("PUT "+options.BaseURL+"/api/member", wrapper.PutApiMember)
	m.HandleFunc("POST "+options.BaseURL+"/api/member/qualification", wrapper.PostApiMemberQualification)
	m.HandleFunc("GET "+options.BaseURL+"/api/member/qualifications", wrapper.GetApiMemberQualifications)
	m.HandleFunc("GET "+options.BaseURL+"/api/member/requirement/initial", wrapper.GetApiMemberRequirementInitial)
	m.HandleFunc("GET "+options.BaseURL+"/api/member/requirements/initial", wrapper.GetApiMemberRequirementsInitial)
	m.HandleFunc("GET "+options.BaseURL+"/api/member/requirements/recurring", wrapper.GetApiMemberRequirementsRecurring)
	m.HandleFunc("GET "+options.BaseURL+"/api/member/subordinates", wrapper.GetApiMemberSubordinates)
	m.HandleFunc("GET "+options.BaseURL+"/api/members", wrapper.GetApiMembers)
	m.HandleFunc("GET "+options.BaseURL+"/api/organization", wrapper.GetApiOrganization)
	m.HandleFunc("GET "+options.BaseURL+"/api/potentialSupervisors", wrapper.GetApiPotentialSupervisors)
	m.HandleFunc("POST "+options.BaseURL+"/api/qualification", wrapper.PostApiQualification)
	m.HandleFunc("PUT "+options.BaseURL+"/api/qualification", wrapper.PutApiQualification)
	m.HandleFunc("GET "+options.BaseURL+"/api/qualifications", wrapper.GetApiQualifications)
	m.HandleFunc("GET "+options.BaseURL+"/api/ranks", wrapper.GetApiRanks)
	m.HandleFunc("POST "+options.BaseURL+"/api/requirement", wrapper.PostApiRequirement)
	m.HandleFunc("PUT "+options.BaseURL+"/api/requirement", wrapper.PutApiRequirement)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW2/bOBb+K4R2H2YATezMdHa3fktbIwjQbtqkfSqCgJGObLYSqZCUC2/h/77gRTIl",
	"URc7jpsAebMlXg6/850Lz9HPIGJZzihQKYLZz0BES8iw/jnnnHH1I+csBy4J6McZCIEXoH7KdQ7BLBCS",
	"E7oINpsw4HBfEA5xMPtaDbwJy4Hs7htEMtiEwQUlkuD0A2R3wK/MpAyoVKvGICJOckkYDWblSMS3gxAW",
	"giwoxEgyhFGmFwnChpzloNu7tUfWUJ87BTlmQIylPm/CeIZlMAvUgz8kySAI2/OMPLck9q7qnMM/pIVi",
	"uVprblg7480mDAyebZ3hOCPU2euOsRQwVfLEROC7FGL/24RwIW8pzsB7mAXHsf9Nx+lT3LecKHLgKyJY",
	"J3qFAN4xvYGbxscR393bWac8Q2gxcgDx8dYA/KnAKUlIhA1Hm5StvUZnhyCrItxtOehQVLx35dyZjK3Z",
	"TSnb9GzhVgehQ0xiPMCtw34zXEKmf/yTQxLMgn9Mtq5sYv3YxPUtmwohzDleq/+dVKRMGqE8BhwVXP15",
	"BIF8HNYi+rh4hel30UZxfuoVe/6n//Ff/sev/I//9j/+l//xv/2P/+N//HqYf/PTQJ9Ey62l1DJpCfR+",
	"enW9lhexUnUj4k419hlFHjtP2eOSCMn4egdadkHztlrUZ0AdNnvYGKjtYHQg9OJw06t+54wjibDdAiWM",
	"d3NhrK6VrLspezRwzR0aBDTI1CyhfoQYr8XtCqckvk1MQmg3JVTCAngtEQBaZHtb6mD6YEOBP1fZw5eP",
	"iIAK0AQ40Mi/uHkwShE24SgP4a5s12k7rY0+dcL0FkSm6t3Hy6vPOEVnHy+QAL7SrFsBF4av05PTk6mS",
	"jOVAcU6CWfDXyfRkqqiJ5VIDMcE5mdhEx8kZmdDqV8rXiFzEajcm5FlO3tVGq7U4zkACF8Hs689ApZfB",
	"fQF8XR50FrimGgczyQsI7QXDh9iNGixyRoXR1p/Tadsar4soAiGSIkVWfnXUV9NX7aFGVESZRAkraKyV",
	"IvFCCVxmyjc668wyrFxlYM+4teZNaKACugNSc/rEgDLSHxAnc8I2TClbmGtGLz7v9ShzYBDyDYvXxlNS",
	"af0PzvPUGuXkmzBOeQtH3TvlWIgfjO9+XdjUbVSBvvEDO1qyvgBrgdS7dmrKAKgVdXqwnc093rPxBdVe",
	"HUUcYqDKJ4ma7s8KuVTPbb5e54DWokqD5BKQI5xLBlbIMWxQw3aktF18F2kRKyRiSae8WWXdC/CIew5K",
	"2uNb9fHIZwBA6vQ7uYotyucg3UzI40N6qVCBu69nwGl6mWh9jAEj3MGVbFqB+ebJ+A+rlIgDlhAjUWk0",
	"XRtFTo/nSlY4LUA0aPFWSzbEjMJHjOKFFwc07SLXF4Bjk8Jsi6z2dnAuYfD3MeT8QkUOEUkIxAjsIJe/",
	"X4z8mCJCY7IicYHTXi5vp34AuWSxUHFS3ZY4jiT6QeSyvZJoBKLJfatYZn1nXXhTXkQY1cY36hM97rZe",
	"kxsV2Dw38RHxLfQv5ikjPnjNejXgKYXgOtoeLtZrx1W5qe3Uuw2IcVRfxWdRTUuVKlFO0bW+T6J5ZQV1",
	"dtfFr1P9op/fdX72s104WVhdUDfDEM0lw56U7VNzaIPnDTzeqUzRCi6Zyokam6GEcX2XP5R5PJR7o6p8",
	"XhK2itB9kWS37HCIbqZ84TjdHrqJBt/O2zrxVmcbRHOKeBOnnDTINrf618s0p5Z2UVV6ju1VWwXSp+EE",
	"O9u+/aSzxHImIA6SE1jh1MlmuryhO+9w5HSX3dEV1hpH3fwU4wiapoi0m+SiWZcexVjx6yjrSQR+sbfs",
	"ZuuuLlNFE5+Ohsj7OGwVA3Qd4lIfY6vu6CBnua+vsidrqx7NC297e3n7MXerqQ7/NZCN3u+bjR6M02O4",
	"1mC1KO4YjwnFtnc0WBS8difskV+6Gz7n7PIpJ5SeFLIJexchxpFgUPOXeXV9QAlJJVhW6mwG4vJqc4L+",
	"y+x79bLgKrtNt7UCPzfMhJoDKvuxpgcU+79vegY08eV7j1sVeoPjsmSFfsuYkCgl3yFdI2LLWgbt3z00",
	"E91VoLsi/V6pu1X6YXyBKflfVfLp4dulO/SBaquXO5tC9He2a6NvPDh+XgJyB5keDBGIUCExjaABoMQe",
	"K5XNRZT9NFaxGOZMmmbWdfU14ZDtfvRNeVqm8J4IHYur0yHhyHosm/jgMYNz/enHgzpGqT2c0rL3gNYx",
	"L8gKKCo/2PQ1EfpcrxZU2WBCaNyzz/z0j/nr3yIsAAmggkiygt87PG4py05ZpBchmwV0ihVqDMt9tKAU",
	"fgwEhOFstG1maR/TahHypLK5zlq1t/DcLDnv29bpo7Cn0Hq8nsxgldcJbLptZ+twx45rD8in2pXgngbe",
	"i8Idhf/SJtxBNT6izVXvmd03C89t5zEUqlt1/McP0g8plztpaxeUo5PFjgYKLz8D70HNfCr+iAZgNujI",
	"/rSEe6d9ZrZcYokixs0J4vLDI5MRtHJA3vietS8aXdXq+o/hmlqF7uM5pvE19mcah5pF+J4o9KJof/xp",
	"q+XBsaK7NbJfpNhs/h8AAP//wcZefqg4AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
