openapi: "3.0.0"
info:
  version: 0.1.0
  title: PORTal API server
paths:
  /api/potentialSupervisors:
    summary: Get the list of potential supervisors for a member.
    parameters:
      - name: grade
        required: true
        description: Grade to find potential supervisors for E1-E9(case sensitive)
        in: query
        schema:
          type: string
      - name: id
        description: Member to get potential supervisors for, not required for new members
        in: query
        schema:
          type: string
    get:
      tags:
        - Member
      summary: Get a list of the potential supervisors for a given grade
      responses:
        200:
          description: "List of potential supervisors"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
        400:
          description: Most likely invalid Grade
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Member not found
  /api/member:
    summary: Methods to interact with individual members
    get:
      summary: Get a member
      tags:
        - Member
      parameters:
        - name: id
          required: true
          schema:
            type: string
          in: query
      responses:
        200:
          description: Successful member get
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        404:
          description: Member not found
    put:
      summary: Update an individual member
      tags:
        - Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Member'
                - type: object
                  properties:
                    password:
                      type: string
      responses:
        200:
          description: Successful member update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        400:
          description: Invalid update request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "Member not found"
        500:
          description: Unspecified error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a member
      tags:
        - Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Member'
                - type: object
                  properties:
                    password:
                      type: string
      responses:
        200:
          description: Member created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        400:
          description: Invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/member/subordinates:
    summary: Get subordinates for a member
    get:
      tags:
        - Member
      parameters:
        - name: member_id
          description: ID of member to get subordinates for
          required: true
          schema:
            type: string
          in: query
      responses:
        200:
          description: Successful get
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
        404:
          description: Member not found
        500:
          description: Internal server error
  /api/member/qualifications:
    summary: Get qualifications assigned to a member
    get:
      description: Get a members qualifications
      tags:
        - MemberQualifications
      parameters:
        - name: member_id
          description: ID of member to get qualifications for
          required: true
          schema:
            type: string
          in: query
      responses:
        200:
          description: Successful get
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MemberQualification'
        404:
          description: Member not found
        500:
          description: Internal server error
  /api/member/qualification:
    summary: Interact with individual member qualifications
    post:
      description: Assign a qualification to a member
      tags:
        - MemberQualification
      parameters:
        - name: member_id
          required: true
          schema:
            type: string
          in: query
        - name: qualification_id
          required: true
          schema:
            type: string
          in: query
        - name: assigned_by
          required: true
          schema:
            type: string
          in: query
      responses:
        200:
          description: Qualification assigned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberQualification'
        404:
          description: Member or Qualification not found
        500:
          description: Internal Server Error
  /api/member/requirement/initial:
    summary: Interact with individual member requirements
    get:
      description: Get a member requirement
      tags:
        - Member Requirement
      parameters:
        - name: member_id
          required: true
          schema:
            type: string
          in: query
        - name: requirement_id
          required: true
          schema:
            type: string
          in: query
      responses:
        200:
          description: Successful Member Requirement retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitialMemberRequirement'
        400:
          description: Member or Requirement not found
        500:
          description: Internal server error
  /api/member/requirements/initial:
    summary: Interact with initial requirements for a member
    get:
      description: Get all initial requirements for a member
      tags:
        - Member Requirements
      parameters:
        - name: member_id
          required: true
          schema:
            type: string
          in: query
        - name: qualification_id
          schema:
            type: string
          in: query
      responses:
        200:
          description: Successful get of initial requirements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InitialMemberRequirement'
        400:
          description: Member not found
        500:
          description: Internal server error
  /api/member/requirements/recurring:
    summary: Interact with recurring requirements for a member
    get:
      description: Get all recurring requirements for a member
      tags:
        - Member Requirements
      parameters:
        - name: member_id
          required: true
          schema:
            type: string
          in: query
        - name: qualification_id
          schema:
            type: string
          in: query
      responses:
        200:
          description: Successful get of recurring member requirements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecurringMemberRequirement'
        404:
          description: Member or qualification not found
        500:
          description: Internal server error
  /api/members:
    summary: Methods to bulk retrieve members
    get:
      tags:
        - Members
      parameters:
        - name: filter
          description: Options for filtering retrieved members. No filter returns all members
          schema:
            type: string
            enum:
              - enabled
              - disabled
          in: query
      responses:
        200:
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
        400:
          description: Bad request (most likely invalid filter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/qualifications:
    summary: Methods to bulk retrieve qualifications
    get:
      tags:
        - Qualifications
      responses:
        200:
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Qualification'
  /api/qualification:
    summary: Methods to interact with an individual qualification
    post:
      tags:
        - Qualification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Qualification'
      responses:
        200:
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Qualification'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
    put:
      tags:
        - Qualification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Qualification'
      responses:
        200:
          description: Successful update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Qualification'
        400:
          description: "Invalid update"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
  /api/requirement:
    summary: Methods to interact with an individual qualification
    post:
      tags:
        - Requirement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requirement'
      responses:
        200:
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requirement'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
    put:
      tags:
        - Requirement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requirement'
      responses:
        200:
          description: Successful update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requirement'
        400:
          description: Bad update
        500:
          description: Internal server error
  /api/disableMember:
    summary: Disable a member
    post:
      tags:
        - Member
      parameters:
        - name: id
          schema:
            type: string
          required: true
          in: query
      responses:
        200:
          description: Successful disable
        404:
          description: Member not found
  /api/enableMember:
    summary: Enable a member
    post:
      tags:
        - Member
      parameters:
        - name: id
          schema:
            type: string
          required: true
          in: query
      responses:
        200:
          description: Successful enable
        404:
          description: Member not found
  /api/login:
    summary: Login to the application
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        401:
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/logout:
    summary: Log out of the application
    post:
      tags:
        - Authentication
      responses:
        200:
          description: Successful logout
  /api/organization:
    summary: Get the organization for this instance
    get:
      tags:
        - Meta
      responses:
        200:
          description: The organization of this instance
          content:
            application/json:
              schema:
                required:
                  - organization
                properties:
                  organization:
                    type: string
  /api/ranks:
    summary: Get the ranks that correspond to the given instance
    get:
      tags:
        - Meta
      responses:
        200:
          description: The ranks of this instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ranks'

components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Member:
      type: object
      required:
        - id
        - first_name
        - last_name
        - username
        - grade
        - admin
        - disabled
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        supervisor_id:
          type: string
        grade:
          type: string
        admin:
          type: boolean
        disabled:
          type: boolean
    Qualification:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        initial_requirements:
          type: array
          items: 
            $ref: '#/components/schemas/Requirement'
        recurring_requirements:
          type: array
          items:
            $ref: '#/components/schemas/Requirement'
        notes:
          type: string
    Requirement:
      type: object
      required:
        - id
        - name
        - initial
        - reference
        - type
      properties:
        id:
          type: string
        name:
          type: string
        initial:
          type: boolean
        reference:
          type: string
        notes:
          type: string
        type:
          type: string
        qualification_id:
          type: string
        grade:
          type: string
          enum:
            - E1
            - E2
            - E3
            - E4
            - E5
            - E6
            - E7
            - E8
            - E9
        days_valid_for:
          type: integer
    Ranks:
      type: object
      required:
          - E1
          - E2
          - E3
          - E4
          - E5
          - E6
          - E7
          - E8
          - E9
      properties:
        E1:
          type: string
        E2:
          type: string
        E3:
          type: string
        E4:
          type: string
        E5:
          type: string
        E6:
          type: string
        E7:
          type: string
        E8:
          type: string
        E9:
          type: string
    MemberQualification:
      description: Qualification Assigned to a member
      required:
        - member_id
        - qualification_id
        - date_assigned
        - assigned_by
      properties:
        member_id:
          type: string
        qualification_id:
          type: string
        date_assigned:
          type: string
          format: date-time
        assigned_by:
          type: string
    InitialMemberRequirement:
      description: Initial requirement assigned to a member
      required:
        - member_id
        - requirement_id
        - assigned_by
      properties:
        member_id:
          type: string
        requirement_id:
          type: string
        completed_date:
          type: string
          format: date-time
        assigned_by:
          type: string
        completed_by:
          type: string
    RecurringMemberRequirement:
      description: Recurring requirement assigned to a member
      required:
        - id
        - member_id
        - requirement_id
        - assigned_by
        - completion_history
      properties:
        id:
          type: string
        member_id:
          type: string
        requirement_id:
          type: string
        assigned_by:
          type: string
        completed_by:
          type: string
        completed_date:
          type: string
          format: date-time
        completion_history:
          type: array
          items:
            $ref: '#/components/schemas/RecurringMemberRequirementCompletion'
    RecurringMemberRequirementCompletion:
      description: Recurring requirement completion for a member
      required:
        - id
        - completion_date
        - completed_by
      properties:
        id:
          type: string
        completion_date:
          type: string
          format: date-time
        completed_by:
          type: string