//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Member defines model for Member.
type Member struct {
	Admin        bool    `json:"admin"`
	Disabled     bool    `json:"disabled"`
	FirstName    string  `json:"first_name"`
	Grade        string  `json:"grade"`
	Id           string  `json:"id"`
	LastName     string  `json:"last_name"`
	SupervisorId *string `json:"supervisor_id,omitempty"`
	Username     string  `json:"username"`
}

// PostApiDisableMemberParams defines parameters for PostApiDisableMember.
type PostApiDisableMemberParams struct {
	Id string `form:"id" json:"id"`
}

// PostApiEnableMemberParams defines parameters for PostApiEnableMember.
type PostApiEnableMemberParams struct {
	Id string `form:"id" json:"id"`
}

// GetApiMemberParams defines parameters for GetApiMember.
type GetApiMemberParams struct {
	Id string `form:"id" json:"id"`
}

// PostApiMemberJSONBody defines parameters for PostApiMember.
type PostApiMemberJSONBody struct {
	Admin        bool    `json:"admin"`
	Disabled     bool    `json:"disabled"`
	FirstName    string  `json:"first_name"`
	Grade        string  `json:"grade"`
	Id           string  `json:"id"`
	LastName     string  `json:"last_name"`
	Password     *string `json:"password,omitempty"`
	SupervisorId *string `json:"supervisor_id,omitempty"`
	Username     string  `json:"username"`
}

// GetApiPotentialSupervisorsParams defines parameters for GetApiPotentialSupervisors.
type GetApiPotentialSupervisorsParams struct {
	// Grade Grade to find potential supervisors for E1-E9(case sensitive)
	Grade string `form:"grade" json:"grade"`

	// Id Member to get potential supervisors for
	Id string `form:"id" json:"id"`
}

// PostApiMemberJSONRequestBody defines body for PostApiMember for application/json ContentType.
type PostApiMemberJSONRequestBody PostApiMemberJSONBody

// PutApiMemberJSONRequestBody defines body for PutApiMember for application/json ContentType.
type PutApiMemberJSONRequestBody = Member

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/disableMember)
	PostApiDisableMember(w http.ResponseWriter, r *http.Request, params PostApiDisableMemberParams)

	// (POST /api/enableMember)
	PostApiEnableMember(w http.ResponseWriter, r *http.Request, params PostApiEnableMemberParams)
	// Get a member
	// (GET /api/member)
	GetApiMember(w http.ResponseWriter, r *http.Request, params GetApiMemberParams)
	// Create a member
	// (POST /api/member)
	PostApiMember(w http.ResponseWriter, r *http.Request)
	// Update an individual member
	// (PUT /api/member)
	PutApiMember(w http.ResponseWriter, r *http.Request)
	// Get a list of the potential supervisors for a given grade
	// (GET /api/potentialSupervisors)
	GetApiPotentialSupervisors(w http.ResponseWriter, r *http.Request, params GetApiPotentialSupervisorsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiDisableMember operation middleware
func (siw *ServerInterfaceWrapper) PostApiDisableMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiDisableMemberParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDisableMember(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiEnableMember operation middleware
func (siw *ServerInterfaceWrapper) PostApiEnableMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiEnableMemberParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiEnableMember(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMember operation middleware
func (siw *ServerInterfaceWrapper) GetApiMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMemberParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMember(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiMember operation middleware
func (siw *ServerInterfaceWrapper) PostApiMember(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiMember operation middleware
func (siw *ServerInterfaceWrapper) PutApiMember(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPotentialSupervisors operation middleware
func (siw *ServerInterfaceWrapper) GetApiPotentialSupervisors(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiPotentialSupervisorsParams

	// ------------- Required query parameter "grade" -------------

	if paramValue := r.URL.Query().Get("grade"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "grade"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "grade", r.URL.Query(), &params.Grade)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "grade", Err: err})
		return
	}

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPotentialSupervisors(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/disableMember", wrapper.PostApiDisableMember)
	m.HandleFunc("POST "+options.BaseURL+"/api/enableMember", wrapper.PostApiEnableMember)
	m.HandleFunc("GET "+options.BaseURL+"/api/member", wrapper.GetApiMember)
	m.HandleFunc("POST "+options.BaseURL+"/api/member", wrapper.PostApiMember)
	m.HandleFunc("PUT "+options.BaseURL+"/api/member", wrapper.PutApiMember)
	m.HandleFunc("GET "+options.BaseURL+"/api/potentialSupervisors", wrapper.GetApiPotentialSupervisors)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yX227jNhCGX4Vge9ECcnyI41q627ZGkKLBBk33KggWI3FkM6VILofy1gj87gUl+Sw7",
	"cRuke2VB4uGfb34Ox888M4U1GrUnnjxzymZYQPU4cc648GCdsei8xOp1gUQwxfDoFxZ5wsk7qad8uYy4",
	"wy+ldCh48rAe+BitBpr0CTPPlxG/xSLFlsVBFFJvLZ0aoxB0mCIkQarC0m1fc+nIf9ZQtAmL+NSBaP8i",
	"RetrBaeWo9Kim0sy7vOR+SWhOzJ9D5MUfEf+9t5b66xiiBpGW0AOAYc9pM5Ntbv0Kny7+/jHn6DYh7sb",
	"Rujm6HjE5+hIGs0T3rvoX/SCcGNRg5U84ZcXvYsej7gFP6uS0wUru82uWwk05MNvSCN4afSNCLsZ8h+s",
	"/HVndFjLQYEeHfHk4ZmHXPMvJboFj3iNq+axAeRdiVFjyzaYj2EwWaOpdtCg1ws/Ailz0vo6uvsyy5Ao",
	"LxVr9IdQh73h4dBaKtPGs9yUWlT58jANgle2fawsUBTgFjzhTYwMWFF/XkY1KtRnkJrobwxUrf4NOdUR",
	"HmIq1oCm2MLnGgOe9weTGe1RV4LAWiWzSlL3iYzeFMrw9L3DnCf8u+6mknabMtptZFcH8ijpGgAL0Z9F",
	"e4P2Gv2Ga2saTnpvDTdAQ/I/G7E4CwEo9TGv8vEaGNF+1bdA9NU40V4s92rb43K3gob0Lv+XFDZJyRyC",
	"R8FonVG1qBP5diLqu7hFw42eg5KCzUGVSHu2+KVS9pIzyjZjlG/ii9dy/RayeXggSyvA47unst6WNczP",
	"KAkRv3oPnZ80WcxkLlEwbAZtu+5TrR80k1rIuRQlqJMO3Ey9RT8zgpg3TGqPDjLPvko/O1yJ1teHNSFW",
	"Cep+3ZTRC5fJXduUf2U6/BsKG9qrh3XvWl83m241B0W426Dy38ymoUv4ZMTrPpT34wGkl6PLDvSHcWeY",
	"pledtJ/FncEgT0eY9cbD8XinQUz4vS7zfLHdKSb8ieqXodI2qhoVL8ma6W1d/ZUucTVOe5DHnRhi6Azz",
	"8bADMfY7wzSO+4PRcJT9dKCrkH62L6t6Fy7cjQWlx4Jee2rXlwE4B4s2c/4uyTOTs7UrGG3l+L2O8q0h",
	"z5T8C9WCyeZYX1dU/9MFr5rg/AzbA2S5cQzYVM5Rs9X/hbaav9tE7UqphIYjmEstTuwz6Xcm8Q8ZEDJC",
	"TdLLOf4YHNPSkq20vL4ri44Q8iY0SsdlHRFwfk+4Cz8gV6e81aCvq9NFMMU/AQAA//+l+nGIWw8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
